theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Handbuch zum BSB-LPB-LAN-Adapter
description: Online-Version des Handbuchs für den LAN-Adapter für Heizungssysteme mit BSB, LPB und PPS-Schnittstelle und die BSB-LAN-Software. 
url: https://1coderookie.github.io/BSB-LPB-LAN
author: Ulf Dieckmann
lang: de-DE
