theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Handbuch zum BSB-LPB-LAN Adapter
description: Das Handbuch zum LAN-Adapter für Heizungssysteme mit BSB, LPB und PPS-Schnittstelle und zur BSB-LAN Software. 
url: {{ site.github.repository_url }}
author: Ulf Dieckmann
lang: de-DE
