theme: pmarsceill/just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Handbuch zum BSB-LPB-LAN-Adapter 
description: Handbuch zum LAN-Adapter für Heizungssysteme mit BSB, LPB und PPS-Schnittstelle und zur BSB-LAN-Software. 
url: https://1coderookie.github.io/BSB-LPB-LAN
author: Ulf Dieckmann
lang: de-DE
