theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Handbuch zur BSB-LAN Hard- & Software
url: "https://1coderookie.github.io"
baseurl: "/BSB-LPB-LAN"
author: Ulf Dieckmann
lang: de-DE
